services:
  server-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-monitor
    restart: unless-stopped
    ports:
      - "8000:8000"  # <-- Только этот порт
    volumes:
      - /run/systemd/system:/run/systemd/system
    environment:
      - SYSTEMD_OFFLINE=0
    privileged: true