services:
  server-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-monitor
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Монтируем сокет systemd для systemctl
      - /run/systemd/system:/run/systemd/system
    environment:
      # Убедимся, что systemd видит хост-систему
      - SYSTEMD_OFFLINE=0
    privileged: true  # Даем контейнеру привилегии для доступа к systemd